easy_admin:
    site_name: 'Blog Admin'
    entities:
        # List the entity class name you want to manage
        #- App\Entity\Comment
        Comment:
            class: App\Entity\Comment
        #- App\Entity\Post
        Post:
            class: App\Entity\Post
        #- App\Entity\User
        User:
            class: App\Entity\User
    design:
        menu:
            - { entity: 'Post', default: true }
            - Comment
            - User
